-- ADICIONANDO DATA COM INTERVALOS

-- DATE_ADD 	-- DATA DE AGORA ADICIONANDO 2 ANOS E 4 MESES
-- CURDATE()	-- PEGA DATA DE HOJE - APENAS DATA
-- DATE_ADD()	-- COMANDO PARA ADICIONAR DATA QUE ESTA ENTRE PARENTESE
-- (AQUI , )	-- ANTES DA VIRGULA A DATA NA QUAL VAI OCORRER A SOMA
-- INTERVAL		-- INDICA QUE HAVERÁ UM INTERVALO
-- ( , AQUI)	-- DEPOIS DA VIRGULA ESPECIFICAMOS QUE É UM INTERVALO ENTRE "" O TEMPO E DEPOIS
-- 				-- ESPECIFICAMOS O QUE REPRESENTA CADA NUMERO


-- ADICIONANDO DOIS ANOS E 4 MESES
SELECT CURDATE() hoje,
	DATE_ADD(CURDATE(), INTERVAL "2-4" YEAR_MONTH) AS acrescimo;

-- ADICIONANDO 2 MESES
SELECT CURDATE() HOJE,
	DATE_ADD(CURDATE(), INTERVAL "2" MONTH) AS acrescimo;
    
-- ADICIONANDO 3 ANOS
SELECT CUrDATE() HOJE,
	DATE_ADD(CURDATE(), INTERVAL "3" YEAR) AS acrescimo;

-- ADICIONANDO 90 DIAS
SELECT CURDATE() HOJE,
	DATE_ADD(CURDATE(), INTERVAL "90" DAY) AS ACRESCIMO;

-- ADICIONANDO 3 HORAS
SELECT NOW() HOJE,
	DATE_ADD(NOW(), INTERVAL "3" HOUR) AS ACRESCIMO;

-- ADICIONANDO 15 MINUTOS
SELECT NOW() HOJE,
	DATE_ADD(NOW(), INTERVAL "15" MINUTE) AS ACRESCIMO;
    
