-- FORMATANDO DATAS

-- Case sensitive na formatação de datas entre aspas ''

-- Padrão de datas utuilizado no Brasil


-- %Y	- 4 digitos
SELECT DATE_FORMAT(NOW(), '%d/%m/%Y')RETORNO
-- %y	- 2 digitos
SELECT DATE_FORMAT(NOW(), '%d/%m/%y')RETORNO
-- %M	- Nome do Mês
SELECT DATE_FORMAT(NOW(), '%d/%M/%y')RETORNO

SELECT DATE_FORMAT(NOW(), '%m/%y')RETORNO


-- exemplo
USE sakila;

SELECT 	last_update,
		DATE_FORMAT(last_update, '%m/%Y')
FROM film;

-- exemplo
-- %W	- DIA DA SEMANA
SELECT 	NOW() AS DATA_HORA,
		MONTHNAME(NOW()) MES,
        DATE_FORMAT(NOW(), '%W %M %Y') DATA1,
        DATE_FORMAT(NOW(), '%H:%i:%s') HORA;
        
-- FUNÇÃO CONCAT PARA TRAZER A DATA POR EXTENSO
SELECT	CONCAT('HOJE É ',
				DATE_FORMAT(NOW(), '%d'),' DE ',
                DATE_FORMAT(NOW(), '%M'),' DE ',
                DATE_FORMAT(NOW(), '%Y')) DATA_EXTENSO;

-- NOME DO DIA
SELECT DAYNAME(CURDATE()) RETORNO;
SELECT DAYNAME(NOW()) RETORNO;

-- DIA DA SEMANA - DOMINGO 1°
SELECT DAYOFWEEK(CURDATE()) RETORNO;

-- DIA DO MES
SELECT DAYOFMONTH(CURDATE()) RETORNO;

-- DIA DO ANO
SELECT DAYOFYEAR(CURDATE()) RETORNO;

-- EXTRAINDO INFORMAÇÃO DE DATA
SELECT EXTRACT(YEAR FROM NOW()) RETORNO;
SELECT EXTRACT(YEAR FROM '1986-05-11') RETORNO;
SELECT EXTRACT(MONTH FROM '1986-05-11') RETORNO;
SELECT EXTRACT(DAY FROM '1986-05-11') RETORNO;

-- RETORNA O ULTIMA DIA DO MES - 30,31,28
SELECT LAST_DAY(CURDATE()) RETORNO;


