-- DCL Data Control Language
-- USADA PARA DEFINIR ACESSO / CONTROLE DOS DADOS


-- GRANT  - ATRIBUI PRIVILÉGIOS DE ACESSO DO USUÁRIO A OBJETOS DO BANCO DE DADOS
-- REVOKE - REMOVE OS PRIVILÉGIOS DE ACESSO AOS OBJETOS OBTIDOS COM O COMANDO GRANT


-- CRIAR LOGIN 'ALUNO' E DAR PERMISSÃO NO BANCO E OBJETOS - PERMISSAO APENAS DE SELECT
-- ISSO FOI FEITO PELO PROGRAMA EM AULAS MAIS ADIANTES SERÁ FEITO PELO CÓDIGO



-- CONCEDENDO PRIVILÉGIOS (COMANDO GRANT)
-- CONCEDE ACESSO AO COMANDO UPDATE AO USUARIO APENAS NA TABELA 'funcionarios'
GRANT UPDATE ON funcionarios TO 'ALUNO'@'localhost';


-- CONCEDENDO ACESSO DE UPDATE PARA ALUNO EM TODAS AS TABELAS
GRANT UPDATE ON *.* TO 'ALUNO'@'localhost';


-- CONCEDER ACESSO AO COMANDO DELETE PARA ALUNO
GRANT DELETE ON funcionarios TO 'ALUNO'@'localhost';
GRANT DELETE ON *.* TO 'ALUNO'@'localhost';


-- CONCEDER ACESSO AO COMANDO INSERT PARA ALUNO
GRANT INSERT ON funcionarios TO 'ALUNO'@'localhost';


-- CONCEDER ACESSO AO COMANDO SELECT PARA ALUNO
GRANT SELECT ON funcionarios TO 'ALUNO'@'localhost';


-- COMBINAÇÃO DE VÁRIOS COMANDOS
GRANT SELECT, INSERT ON funcionarios TO 'ALUNO'@'localhost';


-- CONCEDENDO SELECT COM LIMITAÇÃO DE CAMPOS
GRANT SELECT (nome, setor) ON funcionarios TO 'ALUNO'@'LOCALHOST';


-- CONCEDENDO ACESSO PARA EXECUTAR PROCEDURE
-- TESTE.proc_quadrado (ANTES DO '.' NOME DA TABELA) . (DEPOIS DO '.' NOME DA PROCEDURE)
GRANT EXECUTE ON PROCEDURE TESTE.proc_quadrado TO 'ALUNO'@'localhost';


-- CONCEDENDO TODOS OS PRIVILÉGIOS EM UMA TABELA
GRANT ALL PRIVILEGES ON funcionarios TO 'ALUNO'@'localhost';
-- EM TODO BANCO DE DADOS
GRANT ALL PRIVILEGES ON * . * TO 'ALUNO'@'localhost';


-- RECARREGANDO PRIVILÉGIOS
FLUSH PRIVILEGES


-- VISUALIZAR OS PRIVILÉGIOS DE DETERMINADO USUARIO NO BANCO DE DADOS
SELECT * FROM mysql.user WHERE User='ALUNO';




-- REMOVENDO PRIVILÉGIOS, NEGANDO ACESSO (COMANDO REVOKE)



-- NEGAR ACESSO DE ATUALIZAÇÃO DE DADOS
REVOKE UPDATE ON funcionarios FROM 'ALUNO'@'localhost';
REVOKE UPDATE ON *.* FROM 'ALUNO'@'localhost';


-- NEGAR ACESSO DE EXCLUSÃO DE DADOS
REVOKE DELETE ON *.* FROM 'ALUNO'@'localhost';


-- NEGAR ACESSO A INSERÇÃO DE DADOS
REVOKE INSERT ON *.* FROM 'ALUNO'@'localhost';


-- NEGAR ACESSO A SELEÇÃO DE DADOS
REVOKE SELECT ON *.* FROM 'ALUNO'@'localhost';


-- NEGAÇÃO MULTIPLA
REVOKE SELECT, INSERT ON funcionarios FROM 'ALUNO'@'localhost';


-- NEGANDO SELECT COM LIMITAÇÃO DE CAMPOS
REVOKE SELECT (nome, setor) ON funcionarios FROM 'ALUNO'@'localhost';


-- NEGANDO ACESSO DE EXECUIÇÃO DE PROCEDURE
REVOKE EXECUTE ON PROCEDURE proc_quadrado FROM 'ALUNO'@'localhost';


-- NEGANDO ACESSO A TODOS OS PRIVILÉGIOS, PRIMEIRO EM UM OBETO, DEPOIS EM TODOS
REVOKE ALL PRIVILEGES ON funcionarios FROM 'ALUNO'@'localhost';
REVOKE ALL PRIVILEGES ON *.* FROM 'ALUNO'@'localhost';




FLUSH PRIVILEGES;
SELECT * FROM mysql.user WHERE User='ALUNO';