-- FUNÇÕES DE INFORMAÇÃO


SELECT CHARSET('123') RETORNO1, CHARSET('ABC') RETORNO2;


USE world;

SELECT	name, CHARSET(name)Nome,
		continent, CHARSET(continent)Continente,
        population, CHARSET(population) Populacao
FROM country;


-- CHARSET CONVERSOES
SELECT	CHARSET(CONVERT(name USING utf8))Nome,
		CONVERT(name USING utf8) Nome,
        CHARSET(continent)Continente,
        CHARSET(population)Populacao
FROM country;


-- COLLATION
USE curso;
SELECT COLLATION('ABC');

SELECT COLLATION(nome) FROM alunos;


-- DESCOBINDO ID DA CONEXAO
SELECT CONNECTION_ID();


-- TRAZENDO INFORMAÇÃO DO USUARIO CONNECTADO
SELECT CURRENT_USER();
SELECT CURRENT_USER;
SELECT USER();
SELECT SESSION_USER();
SELECT SYSTEM_USER();


-- VERIFICANDO DATABASE SELECIONADO
USE sakila;
SELECT DATABASE();


-- verificando usuarios
SELECT * FROM mysql.user;


-- TRAZENDO LINHAS LIDAS
USE curso;
SELECT SQL_CALC_FOUND_ROWS nome_mun FROM senso;
SELECT FOUND_ROWS();


-- RETORNANDO ULTIMO ID INSERIDO
INSERT INTO alunos (nome) VALUES ('CATARINA');
INSERT INTO alunos (nome) VALUES ('GREG'), ('MARLA'),('JACK');
SELECT LAST_INSERT_ID();


-- VERIFICANDO SCHEMA SELECIONADO (TABELA)
USE curso;
SELECT SCHEMA();


-- VERIFICANDO VERSAO DO MYSQL
SELECT VERSION();