-- PROCEDURES INOUT
-- ELA RECEBE O VALOR E DEVOLVE A ALTERAÇÃO, MODIFICANDO O VALOR ORIGINAL DA VARIAVEL

-- VALOR PASSADO NA VARIAVEL IRA REFLETIR NO VALOR DA VARIAVEL EXTERNA
DELIMITER //
CREATE PROCEDURE proc_aumento(INOUT valor DECIMAL(10,2), taxa DECIMAL(10,2))

BEGIN
	SET valor = valor+valor*taxa/100;
END //
DELIMITER ;

-- TESTANDO: CIANDO VARIAVEL E PASSANDO PARAMETRO MODIFICADO:
SET @valor=30.00;
SELECT @valor;

-- EXECUTANDO A PROCEDRE:
CALL proc_aumento(@valor, 25.00);

-- VERIFICANDO O VALOR DA VARIAVEL:
SELECT @valor;

 