-- COMANDO TCL - LINGUAGEM DE TRANSACAO
-- TCL EXECUTA AÇÕES NO BANCO DE DADOS EM BLOCOS.
-- SALVA E RETORNA PARA PONTOS DESEJADOS E PROGRAMADOS.
 
-- CRIANDO TABELA DE TESTE
CREATE TABLE cadastro
(
	nome	VARCHAR(50) NOT NULL,
    docto	VARCHAR(20) NOT NULL
)

-- INICIAR TRANSAÇÃO
START TRANSACTION;

-- INSERE OS REGISTROS

INSERT INTO cadastro VALUES ('Andre', '12341234');
INSERT INTO cadastro VALUES ('Joao', '45879654');
INSERT INTO cadastro VALUES ('Pedro', '85634578');

-- RETORNA TABELA PARA O VALOR ANTERIOR DO START TRANSACTION
-- ROLLBACK;

-- EFETIVA AS INFORMAÇÕES NA TABELA DO BD, OU SEJA, DA UM SAVE
COMMIT;



-- TRANSAÇÃO COM SAVE POINTS
START TRANSACTION;
	INSERT INTO cadastro VALUES ('Andre', '12341234');
		SAVEPOINT P1;
	INSERT INTO cadastro VALUES ('Joao', '45879654');
		SAVEPOINT P2;
	INSERT INTO cadastro VALUES ('Pedro', '85634578');
		SAVEPOINT P3;

-- RETORNA A TABELA PARA O ESTADO ONDE FOI EFETUADO O SAVEPOINT P2
ROLLBACK TO SAVEPOINT P2;

-- SALVA AS INFORMAÇÕES NO BANCO DE DADOS
COMMIT;