

-- COMANDO UNION / UNION ALL


-- SIMULANDO ERRO
-- O COMANDO UNION SÓ FUNCIONA QUANDO OS SELECTS UTILIZAM O MESMO NUMERO DE COLUNAS
SELECT '1', '1', 'ABC'
	UNION
SELECT 'A', 2;


-- EXEMPLO UNION ALL
-- NO COMANDO UNION, O ALIAS É SEMPRE TOMADO PELO PRIMEIRO SELECT:
-- TAMBÉM NESTE EXEMPLO É POSSÍVEL VISUALIZAR OS VALORES DUPLICADOS, PORQUE O UNION ALL PERMITE
-- UTILIZAR APENAS O UNION, MOSTRARIA APENAS UMA LINHA, OU SEJA, APENAS O PRIMEIRO SELECT

SELECT 'A' AS CAMPO1, 'B' AS CAMPO2
	UNION ALL
SELECT 'A' AS CAMPO3, 'B' AS CAMPO4;



-- EXEMPLOS DE UTILIZAÇÃO DO COMANDO


-- EXEMPLO 01 - UNION
SELECT ano, estado
FROM senso
WHERE ano = '2014'
	UNION
SELECT ano, estado
FROM senso
WHERE ano = '2013';


-- EXEMPLO 01 - UNION ALL
-- A DIFERENÇA FOI DE MAIS DE 11 MIL REGISTROS EXIBIDOS
SELECT ano, estado
FROM senso
WHERE ano = '2014'
	UNION ALL
SELECT ano, estado
FROM senso
WHERE ano = '2013';


-- EXEMPLO 02 - UNION
-- ORDER BY DEVE SER ACRESCENTADO SEMPRE NO ULTIMO SELECT
SELECT ano, estado, nome_mun, populacao
FROM senso
WHERE ano = '2014'
AND cod_uf = '11'
UNION
SELECT ano, estado, nome_mun, populacao
FROM senso
WHERE ano = '2013'
AND cod_uf = '11'
ORDER BY nome_mun, ano;


-- EXEMPLO 02 - UNION ALL
-- RESULTADO É O MESMO, PORQUE UMA DAS COLUNAS DIFERENCIA OS REGISTROS, NO CASO A DE POPULAÇÃO
SELECT ano, estado, nome_mun, populacao
FROM senso
WHERE ano = '2014'
AND cod_uf = '11'
UNION ALL
SELECT ano, estado, nome_mun, populacao
FROM senso
WHERE ano = '2013'
AND cod_uf = '11'
ORDER BY nome_mun, ano;